### PR TITLE
Whitespace causing issues in media.php

### PR DESCRIPTION
**Pull request by shreyasborse**
Whitespace causing issues - Parse error: syntax error, unexpected ''' (T_ENCAPSED_AND_WHITESPACE) in *******/wp-admin/includes/media.php on line 1500

https://wordpress.org/support/topic/cant-access-wp-admin-after-move-to-another-host/

### CODE REVIEW

**Comment by alwaysontop617** [comment]
@shreyasborse Can you help me with my project

**Comment by shreyasborse** [comment]
@alwaysontop617 yes, you can PM me at shreyasborse at gmail . com

**Comment by alwaysontop617** [comment]
@shreyasborse Yay, so I am creating a php project, and decided to start a new one. Here is the url. Its not started yet though.

https://github.com/alwaysontop617/SellSpace

**Comment by swissspidy** [comment]
Please note the repo description:

> WordPress, Git-ified. Synced via SVN every 15 minutes, including branches and tags! This repository is just a mirror of the WordPress subversion repository. **Please do not send pull requests. Submit patches to http://core.trac.wordpress.org/ instead**.

**Pull request closed without merging**
