### PR TITLE
Update archive.php

### PR DESCRIPTION
**Pull request by dsikar**
Missing closing bracket.

### CODE REVIEW

**Comment by jrfnl** [comment]
It's not. It's left out on purpose.

**Comment by dotaxis** [comment]
Why is it left out on purpose?

**Comment by jrfnl** [comment]
The short of it is, that it is best practice to leave out the PHP closing tag if it's at the end of a file to avoid "Headers already sent" errors.

This is what the PHP manual says about it:

> If a file is pure PHP code, it is preferable to omit the PHP closing tag at the end of the file. This prevents accidental whitespace or new lines being added after the PHP closing tag, which may cause unwanted effects because PHP will start output buffering when there is no intention from the programmer to send any output at that point in the script. 

Ref: http://php.net/manual/en/language.basic-syntax.phptags.php

This article is also a good explanation of it: https://github.com/dseguy/clearPHP/blob/master/rules/leave-last-closing-out.md

**Comment by JQOz** [comment]
hi, can I use 'twentyfourteen' as a starter theme to make a premium theme to sell on theme forest?

**Pull request closed without merging**
