### PR TITLE
Preventing directory listing

### PR DESCRIPTION
**Pull request by elbakai**
Preventing directory listing by using .htaccess file and also by creating index.html file inside all created folder in uploads.

### CODE REVIEW

**Comment by swissspidy** [comment]
Hi there,

This repository is just a mirror of the WordPress subversion repository. Please do not send pull requests. Submit patches to http://core.trac.wordpress.org/ instead.

**Comment by jonathanbossenger** [comment]
Issues are disabled for this repo, so I am hijacking this thread (apologies).

Could I suggest that the the rule of 

`This repository is just a mirror of the WordPress subversion repository. Please do not send pull requests. Submit patches to http://core.trac.wordpress.org/ instead`

be amended with

`unless you are going to use the PR and [this tool](https://rmccue.io/patch/) to submit it is a patch to Trac`

**Comment by swissspidy** [comment]
Patches should ideally be based on the development repository (develop.git.wordpress.org or https://github.com/wordpress/wordpress-develop), not the repository containing the actual builds (like this one).

For suggestion like yours, I recommend asking on [Slack](https://make.wordpress.org/chat/).

**Comment by jonathanbossenger** [comment]
Ah, that is fair enough. I wasnt aware of the development repo. Thanks

**Comment by wordpress-tema** [comment]
Hello i have played with error settings for [wordpress](http://www.wpressforum.com) page with no error. I deleted and reinstalled, but there was no improvement. What needs to be done in this regard?

**Pull request closed without merging**
