### PR TITLE
Remove Hello Dolly

### PR DESCRIPTION
**Pull request by mpsparrow**
Everyone just deletes it the second they make there website.

### CODE REVIEW

**Comment by ncbateman** [comment]
inb4: The description of this repo is: WordPress, Git-ified. Synced via SVN every 15 minutes, including branches and tags! This repository is just a mirror of the WordPress subversion repository. Please do not send pull requests. Submit patches to http://core.trac.wordpress.org/ instead.

**Comment by gpspake** [comment]
lol

**Comment by patpetit** [comment]
And it's dumb to want to remove this file. Any new developper doesn't know how to make a brand new and simple plugins. At least, with Hello Dolly, they know :)
It's just a file, so it's not really boring after all.

**Comment by afilina** [comment]
It takes little effort to remove it when you already know how to make plugins. For a new WP developer, it would take a lot more effort to try and figure out how to make a plugin without this example. As a result, fewer people would be discouraged and more people will create plugins, which is for your own benefit.

**Comment by shawnhooper** [comment]
Agreed with @patpetit  and @afilina, it's a great teaching tool.

**Comment by ncbateman** [comment]
also, lets not forget 'This is not just a plugin, it symbolizes the hope and enthusiasm of an entire generation summed up in two words sung most famously by Louis Armstrong.'

**Comment by nickrouty** [comment]
@ncbateman haha.. nice.

**Comment by helenhousandi** [comment]
I don't think we need to be calling anything "dumb" here. This already exists in Trac, let's not rehash or pile on here.

**Pull request closed without merging**
