### PR TITLE
Repair display custom avatars

### PR DESCRIPTION
**Pull request by Monter**
Prior to the change, the default 'mystery' avatar was displayed instead of your own

### CODE REVIEW

**Comment by LiveChief** [comment]
"WordPress, Git-ified. Synced via SVN every 15 minutes, including branches and tags! This repository is just a mirror of the WordPress subversion repository. Please do not send pull requests. Submit patches to http://core.trac.wordpress.org/ instead. http://wordpress.org/"


> Please do not send pull requests. Submit patches to http://core.trac.wordpress.org/ instead. http://wordpress.org/

**Comment by Monter** [comment]
You are publishing your code here, so GitHUB users will be sending their updates here because they have an account here. Since you can synchronize changes one way, do the opposite. I'm not interested in any trac and I'm not going to learn a new system or set up another account.

**Comment by mrtwebdesign** [comment]
WP core developers are heavily invested in the Trac system. WordPress is reflected here for our convenience. I appreciate your desire to improve the code base, but if you want to be active and involved in WP development, you will need to do that at the source of the activity.
_Monster - "Since you can synchronize changes one way, do the opposite."_
Have you ever had any merge conflicts? Now imagine that en mass between two repo systems.
_Monster - "I'm not going to learn a new system"_
That doesn't work very well as a threat. Developing means learning new things all the time. Best of luck to you. -Matthew

**Comment by Monter** [comment]
But I learn all my life. Today I learned that WordPress developers treat GitHUB as free web hosting with good SEO on Google.

**Comment by brendan-f** [comment]
It clearly states SVN is the version control system used, this is an alternative out of good will - stop crying about it because you're unwilling to read and learn.

**Comment by Monter** [comment]
Here is GitHUB. If you do not accept the issues and pull requests here, remove your code and piss off.

**Pull request closed without merging**
