### PR TITLE
Update customize-controls.min.css

### PR DESCRIPTION
**Pull request by yukipin3**
removed a needless space from the css

### CODE REVIEW

**Comment by JulienMelissas** [comment]
>Please do not send pull requests. Submit patches to http://core.trac.wordpress.org/ instead.

**Comment by DandyDev** [comment]
Seriously? It's 2015. Why hasn't Wordpress moved to Git yet?

**Comment by helenhousandi** [comment]
Indeed, it is 2015, and we use build tools to generate minified files, so no matter which VCS you use (we have a [Git mirror](https://make.wordpress.org/core/2014/01/15/git-mirrors-for-wordpress/), by the way), we don't accept patches for them.

**Comment by SergeyBiryukov** [comment]
The change also appears to be invalid, `.current-panel .accordion-sub-container` is not the same as `.current-panel.accordion-sub-container`.

**Pull request closed without merging**
