### PR TITLE
PNG Image Files Optimization

### PR DESCRIPTION
**Pull request by Dade88**
Lossless optimization of ALL Wordpress PNG files. 99 files out of 133 were
definately changed to a smaller version.

13,72 KB Saved.

### CODE REVIEW

**Comment by marcobiedermann** [comment]
:+1:

**Comment by patpetit** [comment]
There is no push on github, check the previous tickets. 
Btw, the real improvment would be to use a font like font awesome, dedicated to wordpress

**Comment by patpetit** [comment]
Submit your ticket on http://core.trac.wordpress.org/

**Comment by Dade88** [comment]
Sorry patpetit, what I should do in addition to this pull request?

**Comment by shawnhooper** [comment]
@Dade88 -

What @patpetit is trying to say is that WordPress isn't managed through Git.  This repository is simply a copy of the project from the SVN repository.  If you want to submit changes to WordPress core, you'll need to submit a ticket with a patch in the Trac system - the bug tracker used by the WordPress Core team. 

If you've never done this before, I suggest reviewing the Contributor Handbook https://make.wordpress.org/core/handbook/ -- specifically the section on submitting a patch https://make.wordpress.org/core/handbook/working-with-trac/submitting-a-patch/

Hope this helps.

**Comment by helenhousandi** [comment]
PNG files are already automatically optimized via a Grunt task. It may be that other compression algorithms have slightly different effects, already noted at https://core.trac.wordpress.org/ticket/30587

We have and use a custom font (Dashicons); however, we are looking to move away from it for a number of reasons: https://make.wordpress.org/design/2015/01/04/the-future-of-dashicons/

**Comment by Dade88** [comment]
Got it! Thanks for your comments :+1:

**Pull request closed without merging**
