### PR TITLE
Adding a README.md

### PR DESCRIPTION
**Pull request by lambda2**
Github users only see the `readme.html` file, which is unreadable. This readme is a copy of `readme.html`, but in Markdown.

### CODE REVIEW

**Comment by SamBellerose** [comment]
I just starred the project, and honestly this is a must. I was kinda shocked when I saw it was a readme.html file. +1 for this.

**Comment by Ramoonus** [comment]
I`m not sure what the extra value is

**Comment by Nolwennig** [comment]
The `readme.html` is not really readable. 
**+1** for this request

**Comment by SamBellerose** [comment]
@Ramoonus Having a readme.md for a Github project is a must for everyone that look at your project at first for a quick overview. Even tough I can understand html, I was gonna write a readme.md myself and make a pull request for this. It's just a common thing on Github to have this file so that everyone can see at a glance a quick presentation. Wordpress is a high quality project so in my opinion it needs to at least follow Github's rules.

**Comment by tw2113** [comment]
Most anyone grabbing a copy from GitHub already knows all about WordPress. Anyone that would need the readme is grabbing a copy from wordpress.org.

**Comment by swissspidy** [comment]
Please note that WordPress core development happens on https://core.trac.wordpress.org/. This GitHub repository is just a mirror.

There are plans to support contributions from GitHub in the future, but currently pull requests are unregarded.

If you want to add a `readme.md` file for WordPress, please open a ticket for that on Trac.

See also https://core.trac.wordpress.org/ticket/33043

**Pull request closed without merging**
