### PR TITLE
Converted readme.html to readme.md in order to make it readable

### PR DESCRIPTION
**Pull request by LAKSHAY184**

### CODE REVIEW

**Review by jgtorcal — APPROVED** [review]

**Comment by ashwinncj** [comment]
First time seeing this. Was readme file always .html in the repo? Was there a reason for this?

**Review by ashwinncj — APPROVED** [review]
Code looks good.

**Comment by LAKSHAY184** [comment]
> Code looks good.

Thanks

**Comment by LAKSHAY184** [comment]
> First time seeing this. Was readme file always .html in the repo? Was there a reason for this?

Don't know about it. As soon as I came to contribute to wordpress, I saw this, so started working on it.

**Comment by johnbillion** [comment]
Thanks for the pull request @LAKSHAY184 but this is not the correct repo. See here for more information: https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/ . Cheers!

**Pull request closed without merging**
